INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Jorjah','U','JorjahU@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Astrid','RISLE','AstridRISLE@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('RebeccaJane','ISENBURG','RebeccaJaneISENBURG@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Fiona','ERHARDS','FionaERHARDS@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Kayley','ICHISON','KayleyICHISON@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Kole','AGNEW','KoleAGNEW@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Anson','ESORD','AnsonESORD@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Mustabshira','ERNANDEZLOPEZ','MustabshiraERNANDEZLOPEZ@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('AlexanderPreslav','WETHINGTON','AlexanderPreslavWETHINGTON@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('LeonJ','HURSH','LeonJHURSH@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Denvyr','BLANCHE','DenvyrBLANCHE@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('KatieAnn','LAMINCK','KatieAnnLAMINCK@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Mackenzie','ONTBRIAND','MackenzieONTBRIAND@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Davey','AYNG','DaveyAYNG@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('OllieJames','LANTERMAN','OllieJamesLANTERMAN@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Fahad','CHOUDHURY','FahadCHOUDHURY@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (2,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (3,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (4,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (5,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (6,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (7,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (8,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (9,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (10,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (11,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (12,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (13,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (14,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (15,1,1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (16,1,1);

INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('TillyMay','UYPERS','TillyMayUYPERS@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Shanice','UHLE','ShaniceUHLE@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('StacyAnne','EAN','StacyAnneEAN@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Faatamah','HOEPFNER','FaatamahHOEPFNER@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Eduardo','MURABITO','EduardoMURABITO@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Ayisha','ETGEN','AyishaETGEN@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Jed','RISTOFIK','JedRISTOFIK@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Radhia','AUHOF','RadhiaAUHOF@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Alessio','AIDERON','AlessioAIDERON@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Kamran','ARKOSKI','KamranARKOSKI@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (17,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (18,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (19,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (20,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (21,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (22,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (23,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (24,1,2);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (25,1,2);

INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('Dru','HILCHEY','DruHILCHEY@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO Users (User_First_Name, User_Last_Name, User_Email, User_Password, User_Profile_Picture, Two_Factor_Method_Id) VALUES ('MaxxJames','GILETTE','MaxxJamesGILETTE@email.com','$2a$10$PcJ0m/jmm.0jrTbU.T4Ah.qEMX20G7tawN5LyctF7e6uxze5KbS7q','testImage.png',1);
INSERT INTO User_Permissions (User_ID, Shop_ID, Admin_Type_Id) VALUES (26,1,3);



INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Hermiston, Konopelski and Thompson','HermistonKonopelskiandThompson.com','33207','DE Germany',1);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Nolan - Rice','NolanRice.com','38464','IL Israel',2);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Mann, Balistreri and Kunze','MannBalistreriandKunze.com','20625','NO Norway',2);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Kozey, Carter and Ferry','KozeyCarterandFerry.com','14235','MZ Mozambique',1);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Okuneva, Gottlieb and Bayer','OkunevaGottliebandBayer.com','38203','MH Marshall Islands',1);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Mraz, Bahringer and Luettgen','MrazBahringerandLuettgen.com','5367','UA Ukraine',2);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Koepp and Sons','KoeppandSons.com','17268','GM Gambia',2);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Murazik - Sanford','MurazikSanford.com','37089','RW Rwanda',1);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Anderson - Franecki','AndersonFranecki.com','25125','SZ Swaziland',2);
INSERT INTO Shops (Shop_Name, Shop_Website, Shop_Earnings, Shop_Countries, Shop_Active) VALUES ('Erdman - Shields','ErdmanShields.com','35306','GM Gambia',2);
